<?php

declare(strict_types=1);

namespace MageSuite\ElasticsuiteVirtualCategoryIndexer\Console\Command;

class DeleteVirtualCategoryProductsRelations extends \Symfony\Component\Console\Command\Command
{
    protected const COMMAND_NAME = 'magesuite:elasticsuite:virtual-category-products-relations:delete';
    protected const QUESTION_IF_DELETE = 'Are you sure you want to delete all relationships virtucal categories related [yes/no]?';
    protected const QUESTION_IF_DELETE_DEFAULT = 'no';
    protected const QUESTION_IF_DELETE_PARAM_NAME = 'delete';

    protected \MageSuite\ElasticsuiteVirtualCategoryIndexer\Model\ResourceModel\CategoryProductRelations $categoryProductRelationsResourceModel;

    public function __construct(
        \MageSuite\ElasticsuiteVirtualCategoryIndexer\Model\ResourceModel\CategoryProductRelations $categoryProductRelationsResourceModel,
        string $name = null
    ) {
        parent::__construct($name);

        $this->categoryProductRelationsResourceModel = $categoryProductRelationsResourceModel;
    }

    protected function configure()
    {
        $options = [
            new \Symfony\Component\Console\Input\InputOption(
                self::QUESTION_IF_DELETE_PARAM_NAME,
                'f',
                \Symfony\Component\Console\Input\InputOption::VALUE_OPTIONAL,
                'Delete'
            )
        ];
        $this->setName(self::COMMAND_NAME)
            ->setDescription('Clears catalog_category_product table from product IDs generated by the virtual category indexer')
            ->setDefinition($options);

        parent::configure();
    }

    protected function execute(\Symfony\Component\Console\Input\InputInterface $input, \Symfony\Component\Console\Output\OutputInterface $output): int
    {
        $delete = $this->getParam($input, $output, self::QUESTION_IF_DELETE_PARAM_NAME, self::QUESTION_IF_DELETE);

        if ($delete === 'yes') {
            $result = $this->categoryProductRelationsResourceModel->deleteAll();
            $output->writeln(sprintf('<info>Virtual category relations (%s) have been deleted</info>', $result));
        } else {
            $output->writeln('<info>Virtual category relations have not been deleted</info>');
        }

        return 1;
    }

    protected function getParam( // phpcs:ignore
        \Symfony\Component\Console\Input\InputInterface $input,
        \Symfony\Component\Console\Output\OutputInterface $output,
        string $param,
        string $message
    ): string {
        $value = $input->getOption($param);

        if (!$value || !in_array($value, ['yes', 'no'], true)) {
            $question = new \Symfony\Component\Console\Question\Question(sprintf('<question>%s:</question> ', $message), '');

            /** @var \Symfony\Component\Console\Helper\QuestionHelper $questionHelper */
            $questionHelper = $this->getHelper('question');

            $input->setOption(
                $param,
                $questionHelper->ask($input, $output, $question)
            );

            return $this->getParam($input, $output, $param, $message);
        }

        return $value;
    }
}
